// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function $$default(param) {
  React.useState(function () {
        return "";
      });
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: "h-14 absolute flex items-center z-10 w-full justify-center",
                  id: "header"
                }, React.createElement("h1", {
                      className: "text-left text-xl font-bold leading-7"
                    }, Belt_Option.mapWithDefault(Caml_option.null_to_opt(sessionStorage.getItem("name")), "", (function (x) {
                            return x;
                          })) + "님 ")), React.createElement("div", {
                  className: "h-screen pt-14 relative"
                }, React.createElement("div", {
                      className: "px-5 mt-3 pb-16"
                    }, React.createElement("div", undefined, React.createElement("div", {
                              className: "text-center"
                            }), React.createElement("div", {
                              className: "flex items-center"
                            }, React.createElement("div", {
                                  className: "flex-1"
                                }, React.createElement("h2", {
                                      className: "font-bold text-base leading-6 mt-4"
                                    }, "단동 1중 비닐하우스"), React.createElement("p", {
                                      className: "mt-1"
                                    }, "단동 1중 구조에 비닐을 설치하고 측면을 개폐하는 온실 입니다.")), React.createElement("div", {
                                  className: "w-16 h-12 ml-2"
                                }))), React.createElement("div", {
                          className: "flex items-center mt-12"
                        }, React.createElement("div", {
                              className: "flex-1"
                            }, React.createElement("h2", {
                                  className: "font-bold text-base leading-6 mt-4"
                                }, "단동 2중 비닐하우스"), React.createElement("p", {
                                  className: "mt-1"
                                }, "단동 2중 구조에 비닐을 설치하고 측면을 개폐하는 온실 입니다.")), React.createElement("div", {
                              className: "w-16 h-12 ml-2"
                            })), React.createElement("div", {
                          className: "flex items-center mt-12"
                        }, React.createElement("div", {
                              className: "flex-1"
                            }, React.createElement("h2", {
                                  className: "font-bold text-base leading-6 mt-4"
                                }, "단동 3중 비닐하우스"), React.createElement("p", {
                                  className: "mt-1"
                                }, "단동 3중 구조에 비닐과 보온용 커튼을 설치하고 측면을 개폐하는 온실 입니다.")), React.createElement("div", {
                              className: "w-16 h-12 ml-2"
                            })), React.createElement("div", undefined, React.createElement("div", {
                              className: "mt-12 text-center"
                            }), React.createElement("div", {
                              className: "flex items-center"
                            }, React.createElement("div", {
                                  className: "flex-1"
                                }, React.createElement("h2", {
                                      className: "font-bold text-base leading-6 mt-4"
                                    }, "연동 비닐하우스 폭7m x 측고3.5m"), React.createElement("p", {
                                      className: "mt-1"
                                    }, "60x60 각기둥 연동 구조에 비닐을 설치하고 측면을 개폐하는 온실 입니다.")), React.createElement("div", {
                                  className: "w-16 h-12 ml-2"
                                }))), React.createElement("div", undefined, React.createElement("div", {
                              className: "mt-12 text-center"
                            }), React.createElement("div", {
                              className: "flex items-center"
                            }, React.createElement("div", {
                                  className: "flex-1"
                                }, React.createElement("h2", {
                                      className: "font-bold text-base leading-6 mt-4"
                                    }, "연동 비닐하우스 폭8m x 측고5m"), React.createElement("p", {
                                      className: "mt-1"
                                    }, "75x75 각기둥 연동 구조에 측면과 지붕을 개폐하는 온실 입니다.")), React.createElement("div", {
                                  className: "w-16 h-12 ml-2"
                                }))), React.createElement("div", undefined, React.createElement("div", {
                              className: "mt-12 text-center"
                            }), React.createElement("div", {
                              className: "flex items-center"
                            }, React.createElement("div", {
                                  className: "flex-1"
                                }, React.createElement("h2", {
                                      className: "font-bold text-base leading-6 mt-4"
                                    }, "유리온실 폭8m x 측고5m"), React.createElement("p", {
                                      className: "mt-1"
                                    }, "150x75 각기둥 벤로 구조에 피복재로 유리(경질판)를 설치한 온실입니다.")), React.createElement("div", {
                                  className: "w-16 h-12 ml-2"
                                }))))));
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
