// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Router from "next/router";

function $$default(param) {
  var router = Router.useRouter();
  var match = React.useState(function () {
        return "";
      });
  var setName = match[1];
  var name = match[0];
  var match$1 = React.useState(function () {
        return "";
      });
  var setPhone = match$1[1];
  var phone = match$1[0];
  var match$2 = React.useState(function () {
        return false;
      });
  var setAgreePrivcy = match$2[1];
  var agreePrivacy = match$2[0];
  var match$3 = React.useState(function () {
        return false;
      });
  var setValidPhone = match$3[1];
  var match$4 = React.useState(function () {
        return false;
      });
  var setShowPrivacyAgree = match$4[1];
  var handleNameChange = function (e) {
    return Curry._1(setName, e.currentTarget.value);
  };
  var handlePhoneChange = function (e) {
    var value = e.currentTarget.value;
    var reValue = value.replace(/[\D\s^-]+/g, "");
    var spValue = reValue.match(/^(\d{0,3})(\d{0,4})(\d{0,4})/);
    var finValue = Belt_Option.getWithDefault(Belt_Option.map(spValue === null ? undefined : Caml_option.some(spValue), (function (arr) {
                return Belt_Array.reduce(Belt_Array.sliceToEnd(arr, 1), "", (function (acc, num) {
                                  return acc + "-" + num;
                                })).replace(/^[-]+/g, "").replace(/[-]+$/g, "");
              })), phone);
    Curry._1(setValidPhone, (function (param) {
            if (finValue.slice(0, 2) === "01") {
              return finValue.length === 13;
            } else {
              return false;
            }
          }));
    return Curry._1(setPhone, (function (param) {
                  return finValue;
                }));
  };
  var handlePrivacyCheckChange = function (e) {
    var value = e.currentTarget.checked;
    return Curry._1(setAgreePrivcy, (function (param) {
                  return value;
                }));
  };
  var openPrivacyAgree = function (param) {
    return Curry._1(setShowPrivacyAgree, (function (param) {
                  return true;
                }));
  };
  var checkButtonDisabled = function (name, phone, validPhone, agreePrivacy) {
    var name_b = name.length > 1;
    var phone_b = phone !== "";
    return !(name_b && validPhone && phone_b && agreePrivacy);
  };
  var handleNextClick = function (param) {
    sessionStorage.setItem("name", name);
    router.push("/step02");
    
  };
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: "max-w-2xl m-auto flex-col relative",
                  id: "width-limit"
                }, React.createElement("div", {
                      className: "h-14 absolute left-0 z-10",
                      id: "header"
                    }, React.createElement("div", {
                          className: "cursor-pointer w-14 h-14 float-left text-center p-3 hidden"
                        }, React.createElement("svg", {
                              fill: "none",
                              stroke: "currentColor",
                              viewBox: "0 0 24 24",
                              xmlns: "http://www.w3.org/2000/svg"
                            }, React.createElement("path", {
                                  d: "M15 19l-7-7 7-7",
                                  strokeLinecap: "round",
                                  strokeLinejoin: "round",
                                  strokeWidth: "2"
                                })))), React.createElement("div", {
                      className: "h-screen pt-14 relative",
                      id: "content"
                    }, React.createElement("div", {
                          className: "relative"
                        }, React.createElement("div", {
                              className: "mx-5"
                            }, React.createElement("h1", {
                                  className: "font-bold text-2xl leading-8 pt-14"
                                }, "정확한 시공 견적을 위해", React.createElement("br", undefined), React.createElement("span", {
                                      className: "text-gl-primary"
                                    }, "이름"), "과", React.createElement("span", {
                                      className: "text-gl-primary"
                                    }, " 휴대전화번호"), "를", React.createElement("br", undefined), "알려주세요"), React.createElement("form", {
                                  className: "mt-12"
                                }, React.createElement("div", {
                                      className: "flex flex-col justify-around"
                                    }, React.createElement("label", {
                                          className: "flex items-center cursor-pointer border border-solid border-gray-300 rounded-lg"
                                        }, React.createElement("input", {
                                              className: "h-12 w-full px-4 focus:outline-none rounded-lg text-lg",
                                              placeholder: "이름을 입력해주세요",
                                              type: "text",
                                              value: name,
                                              onChange: handleNameChange
                                            }), name !== "" ? React.createElement("span", {
                                                className: "mr-3",
                                                onClick: (function (param) {
                                                    return Curry._1(setName, (function (param) {
                                                                  return "";
                                                                }));
                                                  })
                                              }) : null), React.createElement("div", undefined, React.createElement("label", {
                                              className: "flex items-center cursor-pointer border border-solid border-gray-300 rounded-lg mt-3"
                                            }, React.createElement("input", {
                                                  className: "h-12 w-full px-4 focus:outline-none rounded-lg text-lg",
                                                  lang: "ko-KR",
                                                  inputMode: "numeric",
                                                  pattern: "[0-9]*",
                                                  placeholder: "휴대전화번호를 입력해주세요",
                                                  type: "text",
                                                  value: phone,
                                                  onChange: handlePhoneChange
                                                }), React.createElement("span", {
                                                  className: "mr-3",
                                                  onClick: (function (param) {
                                                      return Curry._1(setPhone, (function (param) {
                                                                    return "";
                                                                  }));
                                                    })
                                                }))), React.createElement("div", {
                                          className: "mt-7 "
                                        }, React.createElement("label", {
                                              className: "text-base flex items-start"
                                            }, React.createElement("input", {
                                                  className: "mr-2 w-5 h-5 cursor-pointer border rounded-md text-green-500 border-gray-400",
                                                  checked: agreePrivacy,
                                                  type: "checkbox",
                                                  onChange: handlePrivacyCheckChange
                                                }), React.createElement("div", {
                                                  className: "inline -mt-1 text-lg leading-5"
                                                }, "(필수)개인정보 수집·이용제공·마케팅 활용에 동의합니다. "), React.createElement("div", {
                                                  className: "flex ml-3 self-center"
                                                }, React.createElement("button", {
                                                      onClick: openPrivacyAgree
                                                    }, React.createElement("svg", {
                                                          height: "16",
                                                          width: "16",
                                                          fill: "none",
                                                          viewBox: "0 0 16 16",
                                                          xmlns: "http://www.w3.org/2000/svg"
                                                        }, React.createElement("path", {
                                                              clipRule: "evenodd",
                                                              d: "M5.25277 14.2472C4.91574 13.9102 4.91574 13.3638 5.25277 13.0267L10.2795 8L5.25277 2.97327C4.91574 2.63624 4.91574 2.0898 5.25277 1.75277C5.5898 1.41574 6.13624 1.41574 6.47327 1.75277L12.1102 7.38975C12.4473 7.72678 12.4473 8.27322 12.1102 8.61025L6.47327 14.2472C6.13624 14.5843 5.5898 14.5843 5.25277 14.2472Z",
                                                              fill: "#757575",
                                                              fillRule: "evenodd"
                                                            }))))))))))), React.createElement("div", {
                      className: "fixed text-center bottom-0 w-full",
                      id: "next-inner"
                    }, React.createElement("div", {
                          className: "min-w-max max-w-2xl p-5"
                        }, React.createElement("button", {
                              className: "w-full bg-gl-primary text-white border border-solid border-transparent rounded-xl ",
                              disabled: checkButtonDisabled(name, phone, match$3[0], agreePrivacy),
                              onClick: handleNextClick
                            }, React.createElement("div", {
                                  className: "w-full disabled:bg-gray-300 text-lg leading-10 font-bold"
                                }, "다음"))))));
}

var Link;

var Router$1;

export {
  Link ,
  Router$1 as Router,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
