// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Caml_array from "rescript/lib/es6/caml_array.js";
import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";

function $$default(param) {
  var match = React.useState(function () {
        return "";
      });
  var setQuestion = match[1];
  var question = match[0];
  var match$1 = React.useState(function () {
        return [];
      });
  var setQArray = match$1[1];
  var qArray = match$1[0];
  var match$2 = React.useState(function () {
        return {
                x: 3,
                y: 1
              };
      });
  var move = match$2[0];
  var match$3 = React.useState(function () {
        return 31;
      });
  var changeNum = match$3[1];
  var num = match$3[0];
  var match$4 = React.useState(function () {
        return 0;
      });
  var setAnswer = match$4[1];
  var questionChange = function (e) {
    return Curry._1(setQuestion, e.currentTarget.value);
  };
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: "flex"
                }, React.createElement("div", {
                      className: "flex w-1/3"
                    }, React.createElement("div", {
                          style: {
                            display: "block",
                            position: "absolute"
                          }
                        }, "1. 문제 붙여 넣기"), React.createElement("textarea", {
                          style: {
                            border: "1px solid #333",
                            height: "700px",
                            marginTop: "30px",
                            width: "260px"
                          },
                          value: question,
                          onChange: questionChange
                        })), React.createElement("div", {
                      className: "w-2/3"
                    }, React.createElement("div", {
                          style: {
                            display: "block"
                          }
                        }, React.createElement("input", {
                              className: "storybook-button storybook-button--medium " + (
                                qArray.length === 0 ? "storybook-button--primary" : "storybook-button--secondary"
                              ),
                              style: {
                                display: "inline-block",
                                margin: "10px"
                              },
                              type: "button",
                              value: "2. Day3 문제읽기",
                              onClick: (function (param) {
                                  console.log("문제읽기");
                                  Curry._1(changeNum, (function (param) {
                                          return question.indexOf("\n");
                                        }));
                                  return Curry._1(setQArray, (function (param) {
                                                return question.split("\n");
                                              }));
                                })
                            }), React.createElement("input", {
                              className: "storybook-button storybook-button--medium " + (
                                qArray.length === 0 ? "storybook-button--secondary" : "storybook-button--primary"
                              ),
                              style: {
                                display: "inline-block",
                                margin: "10px"
                              },
                              disabled: qArray.length === 0,
                              type: "button",
                              value: "3. Day3 문제풀기 (파트1)",
                              onClick: (function (param) {
                                  console.log("문제풀이 (파트1)");
                                  var tempX = 0;
                                  var count = {
                                    contents: 0
                                  };
                                  for(var i = 1 ,i_finish = qArray.length; i < i_finish; ++i){
                                    if (Caml_int32.mod_(i, move.y) === 0) {
                                      tempX = tempX + move.x | 0;
                                      tempX = tempX > (num - 1 | 0) ? tempX - num | 0 : tempX;
                                      var s = {
                                        contents: Caml_array.get(qArray, i)
                                      };
                                      var match = s.contents.substr(tempX, 1);
                                      if (match === "#") {
                                        count.contents = count.contents + 1 | 0;
                                      } else {
                                        console.log(s);
                                      }
                                      Caml_array.set(qArray, i, s.contents);
                                    }
                                    
                                  }
                                  return Curry._1(setAnswer, (function (param) {
                                                return count.contents;
                                              }));
                                })
                            }), React.createElement("input", {
                              className: "storybook-button storybook-button--medium " + (
                                qArray.length === 0 ? "storybook-button--secondary" : "storybook-button--primary"
                              ),
                              style: {
                                display: "inline-block",
                                margin: "10px"
                              },
                              disabled: qArray.length === 0,
                              type: "button",
                              value: "3. Day3 문제풀기 (파트2)",
                              onClick: (function (param) {
                                  console.log("문제풀이 (파트2)");
                                  var tempX = 0;
                                  var count = 0;
                                  var moveArray = [
                                    [
                                      1,
                                      1
                                    ],
                                    [
                                      3,
                                      1
                                    ],
                                    [
                                      5,
                                      1
                                    ],
                                    [
                                      7,
                                      1
                                    ],
                                    [
                                      1,
                                      2
                                    ]
                                  ];
                                  var countArray = [];
                                  for(var j = 0 ,j_finish = moveArray.length; j < j_finish; ++j){
                                    for(var i = 1 ,i_finish = qArray.length; i < i_finish; ++i){
                                      var match = Caml_int32.mod_(i, Caml_array.get(Caml_array.get(moveArray, j), 1));
                                      if (match !== 0) {
                                        console.log("etc");
                                      } else {
                                        tempX = tempX + Caml_array.get(Caml_array.get(moveArray, j), 0) | 0;
                                        if (tempX > (num - 1 | 0)) {
                                          tempX = tempX - num | 0;
                                        }
                                        if (Caml_array.get(qArray, i).substr(tempX, 1) === "#") {
                                          count = count + 1 | 0;
                                        }
                                        
                                      }
                                    }
                                    tempX = 0;
                                    countArray.push(count);
                                    count = 0;
                                  }
                                  
                                })
                            })), React.createElement("div", undefined, "4. 답은", React.createElement("input", {
                              style: {
                                display: "inline-block",
                                margin: "10px",
                                textAlign: "center",
                                width: "40px"
                              },
                              readOnly: true,
                              value: match$4[0].toString()
                            }), "개 입니다."))));
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
