// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";

function part2(arr) {
  var firstSeat = Caml_array.get(arr, 0) - 1 | 0;
  return Belt_Array.reduce(arr, firstSeat, (function (prev, next) {
                if (next === (prev + 1 | 0)) {
                  return prev + 1 | 0;
                } else {
                  return prev;
                }
              })) + 1 | 0;
}

function part1(arr) {
  return Caml_array.get(arr, arr.length - 1 | 0);
}

function makeSeatID(arr) {
  return Belt_Array.reduceWithIndex(arr, 0, (function (acc, x, i) {
                var exp = arr.length - (i + 1 | 0) | 0;
                var increment = Math.pow(2, exp);
                return acc + Math.imul(x, increment) | 0;
              }));
}

function convertBinary($$char) {
  switch ($$char) {
    case "B" :
    case "R" :
        return 1;
    default:
      return 0;
  }
}

function convertArray(str) {
  return Belt_Array.map(str.split(""), convertBinary);
}

function makeArray(input) {
  return input.split("\n");
}

function program(input) {
  return Belt_Array.map(Belt_Array.map(input.split("\n"), convertArray), makeSeatID);
}

function result(input, f) {
  return Curry._1(f, program(input).sort(function (a, b) {
                  return a - b | 0;
                }));
}

function $$default(param) {
  var match = React.useState(function () {
        return "";
      });
  var setQuestion = match[1];
  var question = match[0];
  var match$1 = React.useState(function () {
        return 0;
      });
  var setAnswer = match$1[1];
  var answer = match$1[0];
  var questionChange = function (e) {
    Curry._1(setQuestion, e.currentTarget.value);
    console.log("문제 붙여넣기 완료");
    
  };
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: "flex"
                }, React.createElement("div", {
                      className: "flex w-1/3"
                    }, React.createElement("div", {
                          style: {
                            display: "block",
                            position: "absolute"
                          }
                        }, "1. 문제 붙여 넣기"), React.createElement("textarea", {
                          style: {
                            border: "1px solid #333",
                            height: "700px",
                            marginTop: "30px",
                            width: "260px"
                          },
                          value: question,
                          onChange: questionChange
                        })), React.createElement("div", {
                      className: "w-2/3"
                    }, React.createElement("div", {
                          style: {
                            display: "block"
                          }
                        }, React.createElement("input", {
                              className: "storybook-button storybook-button--medium " + (
                                question.length === 0 ? "storybook-button--secondary" : "storybook-button--primary"
                              ),
                              style: {
                                display: "inline-block",
                                margin: "10px"
                              },
                              disabled: question.length === 0,
                              type: "button",
                              value: "2. Day5 문제풀기 (파트1)",
                              onClick: (function (param) {
                                  console.log("문제풀이 (파트1)");
                                  return Curry._1(setAnswer, (function (param) {
                                                return result(question, part1);
                                              }));
                                })
                            }), React.createElement("input", {
                              className: "storybook-button storybook-button--medium " + (
                                question.length === 0 ? "storybook-button--secondary" : "storybook-button--primary"
                              ),
                              style: {
                                display: "inline-block",
                                margin: "10px"
                              },
                              disabled: question.length === 0,
                              type: "button",
                              value: "2. Day5 문제풀기 (파트2)",
                              onClick: (function (param) {
                                  console.log("문제풀이 (파트2)");
                                  return Curry._1(setAnswer, (function (param) {
                                                return result(question, part2);
                                              }));
                                })
                            }), React.createElement("input", {
                              className: "storybook-button storybook-button--medium " + (
                                answer !== 0 ? "storybook-button--primary" : "storybook-button--secondary"
                              ),
                              style: {
                                display: "inline-block",
                                margin: "10px"
                              },
                              type: "button",
                              value: "클리어",
                              onClick: (function (param) {
                                  console.log("클리어");
                                  Curry._1(setQuestion, (function (param) {
                                          return "";
                                        }));
                                  return Curry._1(setAnswer, (function (param) {
                                                return 0;
                                              }));
                                })
                            })), React.createElement("div", undefined, "답은", React.createElement("input", {
                              style: {
                                display: "inline-block",
                                margin: "10px",
                                textAlign: "center",
                                width: "200px"
                              },
                              readOnly: true,
                              value: answer.toString()
                            }), "입니다."))));
}

export {
  part2 ,
  part1 ,
  makeSeatID ,
  convertBinary ,
  convertArray ,
  makeArray ,
  program ,
  result ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
