// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Caml_array from "rescript/lib/es6/caml_array.js";

function $$default(param) {
  var match = React.useState(function () {
        return "";
      });
  var setQuestion = match[1];
  var question = match[0];
  var match$1 = React.useState(function () {
        return [];
      });
  var setQArray = match$1[1];
  var qArray = match$1[0];
  var match$2 = React.useState(function () {
        return 0;
      });
  var setAnswer = match$2[1];
  var match$3 = React.useState(function () {
        return [];
      });
  var setSeat = match$3[1];
  var questionChange = function (e) {
    return Curry._1(setQuestion, e.currentTarget.value);
  };
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: "flex"
                }, React.createElement("div", {
                      className: "flex w-1/3"
                    }, React.createElement("div", {
                          style: {
                            display: "block",
                            position: "absolute"
                          }
                        }, "1. 문제 붙여 넣기"), React.createElement("textarea", {
                          style: {
                            border: "1px solid #333",
                            height: "700px",
                            marginTop: "30px",
                            width: "260px"
                          },
                          value: question,
                          onChange: questionChange
                        })), React.createElement("div", {
                      className: "w-2/3"
                    }, React.createElement("div", {
                          style: {
                            display: "block"
                          }
                        }, React.createElement("input", {
                              className: "storybook-button storybook-button--medium " + (
                                qArray.length === 0 ? "storybook-button--primary" : "storybook-button--secondary"
                              ),
                              style: {
                                display: "inline-block",
                                margin: "10px"
                              },
                              type: "button",
                              value: "2. Day5 문제읽기",
                              onClick: (function (param) {
                                  console.log("문제읽기");
                                  return Curry._1(setQArray, (function (param) {
                                                return question.split("\n");
                                              }));
                                })
                            }), React.createElement("input", {
                              className: "storybook-button storybook-button--medium " + (
                                qArray.length === 0 ? "storybook-button--secondary" : "storybook-button--primary"
                              ),
                              style: {
                                display: "inline-block",
                                margin: "10px"
                              },
                              disabled: qArray.length === 0,
                              type: "button",
                              value: "3. Day5 문제풀기 (파트1)",
                              onClick: (function (param) {
                                  console.log("문제풀이 (파트1)");
                                  var min = 0;
                                  var max = 127;
                                  var seatID = 0;
                                  var higestSeatID = {
                                    contents: 0
                                  };
                                  var seatArray = [];
                                  for(var i = 0 ,i_finish = qArray.length; i < i_finish; ++i){
                                    for(var j = 0 ,j_finish = Caml_array.get(qArray, i).length; j < j_finish; ++j){
                                      if (j < 7) {
                                        var match = Caml_array.get(qArray, i).substr(j, 1);
                                        if (match === "F") {
                                          max = max - (((max - min | 0) + 1 | 0) / 2 | 0) | 0;
                                        } else {
                                          min = (((max - min | 0) + 1 | 0) / 2 | 0) + min | 0;
                                        }
                                      } else {
                                        if (j === 7) {
                                          seatID = (min << 3);
                                          min = 0;
                                          max = 7;
                                        }
                                        var match$1 = Caml_array.get(qArray, i).substr(j, 1);
                                        if (match$1 === "L") {
                                          max = max - (((max - min | 0) + 1 | 0) / 2 | 0) | 0;
                                        } else {
                                          min = (((max - min | 0) + 1 | 0) / 2 | 0) + min | 0;
                                        }
                                      }
                                    }
                                    seatID = seatID + min | 0;
                                    seatArray.push(seatID);
                                    if (higestSeatID.contents < seatID) {
                                      higestSeatID.contents = seatID;
                                    }
                                    min = 0;
                                    max = 127;
                                  }
                                  Curry._1(setAnswer, (function (param) {
                                          return higestSeatID.contents;
                                        }));
                                  return Curry._1(setSeat, (function (param) {
                                                return seatArray;
                                              }));
                                })
                            }), React.createElement("input", {
                              className: "storybook-button storybook-button--medium " + (
                                qArray.length === 0 ? "storybook-button--secondary" : "storybook-button--primary"
                              ),
                              style: {
                                display: "inline-block",
                                margin: "10px"
                              },
                              disabled: qArray.length === 0,
                              type: "button",
                              value: "3. Day5 문제풀기 (파트2)",
                              onClick: (function (param) {
                                  console.log("문제풀이 (파트2)");
                                  var min = 0;
                                  var max = 127;
                                  var seatID = 0;
                                  var higestSeatID = 0;
                                  var seatArray = [];
                                  for(var i = 0 ,i_finish = qArray.length; i < i_finish; ++i){
                                    for(var j = 0 ,j_finish = Caml_array.get(qArray, i).length; j < j_finish; ++j){
                                      if (j < 7) {
                                        var match = Caml_array.get(qArray, i).substr(j, 1);
                                        if (match === "F") {
                                          max = max - (((max - min | 0) + 1 | 0) / 2 | 0) | 0;
                                        } else {
                                          min = (((max - min | 0) + 1 | 0) / 2 | 0) + min | 0;
                                        }
                                      } else {
                                        if (j === 7) {
                                          seatID = (min << 3);
                                          min = 0;
                                          max = 7;
                                        }
                                        var match$1 = Caml_array.get(qArray, i).substr(j, 1);
                                        if (match$1 === "L") {
                                          max = max - (((max - min | 0) + 1 | 0) / 2 | 0) | 0;
                                        } else {
                                          min = (((max - min | 0) + 1 | 0) / 2 | 0) + min | 0;
                                        }
                                      }
                                    }
                                    seatID = seatID + min | 0;
                                    seatArray.push(seatID);
                                    if (higestSeatID < seatID) {
                                      higestSeatID = seatID;
                                    }
                                    min = 0;
                                    max = 127;
                                  }
                                  seatArray.sort(function (a, b) {
                                        return a - b | 0;
                                      });
                                  for(var i$1 = 1 ,i_finish$1 = seatArray.length; i$1 < i_finish$1; ++i$1){
                                    if (Caml_array.get(seatArray, i$1) !== (Caml_array.get(seatArray, i$1 - 1 | 0) + 1 | 0)) {
                                      Curry._1(setAnswer, (function(i$1){
                                          return function (param) {
                                            return Caml_array.get(seatArray, i$1) - 1 | 0;
                                          }
                                          }(i$1)));
                                    }
                                    
                                  }
                                  
                                })
                            })), React.createElement("div", undefined, "4. 답은", React.createElement("input", {
                              style: {
                                display: "inline-block",
                                margin: "10px",
                                textAlign: "center",
                                width: "200px"
                              },
                              readOnly: true,
                              value: match$2[0].toString()
                            }), "입니다."))));
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
