// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_SetString from "rescript/lib/es6/belt_SetString.js";

function plus(x, y) {
  return x + y | 0;
}

function sum(xs) {
  return Belt_Array.reduce(xs, 0, (function (total, curr) {
                return total + curr | 0;
              }));
}

function mult(xs) {
  return Belt_Array.reduce(xs, 1, (function (total, curr) {
                return Math.imul(total, curr);
              }));
}

var initSet = Belt_SetString.fromArray("abcdefghijklmnopqrstuvwxyz".split(""));

function f(str, init, op) {
  return Belt_Array.reduce(Belt_Array.map(Belt_Array.map(str.split("\n"), (function (s) {
                        return s.split("");
                      })), Belt_SetString.fromArray), init, Curry.__2(op));
}

function multiLineToSet(str) {
  return f(str, Belt_SetString.fromArray([]), Belt_SetString.union);
}

function multiLineToSet2(str) {
  return f(str, initSet, Belt_SetString.intersect);
}

function allToGroup(str) {
  return str.split("\n\n");
}

function program(input, f) {
  return sum(Belt_Array.map(Belt_Array.map(input.split("\n\n"), f), Belt_SetString.size));
}

function part1(input) {
  return program(input, multiLineToSet);
}

function part2(input) {
  return program(input, multiLineToSet2);
}

function $$default(param) {
  var match = React.useState(function () {
        return "";
      });
  var setQuestion = match[1];
  var question = match[0];
  var match$1 = React.useState(function () {
        return [];
      });
  var setQArray = match$1[1];
  var match$2 = React.useState(function () {
        return 0;
      });
  var setAnswer = match$2[1];
  var answer = match$2[0];
  var questionChange = function (e) {
    Curry._1(setQuestion, e.currentTarget.value);
    console.log("문제 붙여넣기 완료");
    
  };
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: "flex"
                }, React.createElement("div", {
                      className: "flex w-1/3"
                    }, React.createElement("div", {
                          style: {
                            display: "block",
                            position: "absolute"
                          }
                        }, "1. 문제 붙여 넣기"), React.createElement("textarea", {
                          style: {
                            border: "1px solid #333",
                            height: "700px",
                            marginTop: "30px",
                            width: "260px"
                          },
                          value: question,
                          onChange: questionChange
                        })), React.createElement("div", {
                      className: "w-2/3"
                    }, React.createElement("div", {
                          style: {
                            display: "block"
                          }
                        }, React.createElement("input", {
                              className: "storybook-button storybook-button--medium " + (
                                question.length === 0 ? "storybook-button--secondary" : "storybook-button--primary"
                              ),
                              style: {
                                display: "inline-block",
                                margin: "10px"
                              },
                              disabled: question.length === 0,
                              type: "button",
                              value: "2. Day6 문제풀기 (파트1)",
                              onClick: (function (param) {
                                  console.log("문제풀이 (파트1)");
                                  return Curry._1(setAnswer, (function (param) {
                                                return program(question, multiLineToSet);
                                              }));
                                })
                            }), React.createElement("input", {
                              className: "storybook-button storybook-button--medium " + (
                                question.length === 0 ? "storybook-button--secondary" : "storybook-button--primary"
                              ),
                              style: {
                                display: "inline-block",
                                margin: "10px"
                              },
                              disabled: question.length === 0,
                              type: "button",
                              value: "2. Day6 문제풀기 (파트2)",
                              onClick: (function (param) {
                                  console.log("문제풀이 (파트2)");
                                  return Curry._1(setAnswer, (function (param) {
                                                return program(question, multiLineToSet2);
                                              }));
                                })
                            }), React.createElement("input", {
                              className: "storybook-button storybook-button--medium " + (
                                answer !== 0 ? "storybook-button--primary" : "storybook-button--secondary"
                              ),
                              style: {
                                display: "inline-block",
                                margin: "10px"
                              },
                              type: "button",
                              value: "클리어",
                              onClick: (function (param) {
                                  console.log("클리어");
                                  Curry._1(setQuestion, (function (param) {
                                          return "";
                                        }));
                                  Curry._1(setQArray, (function (param) {
                                          return [];
                                        }));
                                  return Curry._1(setAnswer, (function (param) {
                                                return 0;
                                              }));
                                })
                            })), React.createElement("div", undefined, "답은", React.createElement("input", {
                              style: {
                                display: "inline-block",
                                margin: "10px",
                                textAlign: "center",
                                width: "200px"
                              },
                              readOnly: true,
                              value: answer.toString()
                            }), "입니다."))));
}

export {
  plus ,
  sum ,
  mult ,
  initSet ,
  f ,
  multiLineToSet ,
  multiLineToSet2 ,
  allToGroup ,
  program ,
  part1 ,
  part2 ,
  $$default ,
  $$default as default,
  
}
/* initSet Not a pure module */
