// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function $$default(props) {
  return React.createElement("div", undefined, props.msg);
}

function getServerSideProps(_ctx) {
  return Promise.resolve({
              props: {
                msg: "코드 작성"
              }
            });
}

export {
  $$default ,
  $$default as default,
  getServerSideProps ,
  
}
/* react Not a pure module */
